# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showTransactions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1106, 756)
        self.tableView = QtGui.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 150, 1011, 521))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.addButton = QtGui.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.addButton.setAutoDefault(False)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 14, 1005, 96))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 7, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 8, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout_2.addWidget(self.dateEdit, 1, 0, 1, 1)
        self.transTypeComboBox = QtGui.QComboBox(self.layoutWidget)
        self.transTypeComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.transTypeComboBox.setObjectName(_fromUtf8("transTypeComboBox"))
        self.gridLayout_2.addWidget(self.transTypeComboBox, 1, 1, 1, 1)
        self.realizedComboBox = QtGui.QComboBox(self.layoutWidget)
        self.realizedComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.realizedComboBox.setObjectName(_fromUtf8("realizedComboBox"))
        self.gridLayout_2.addWidget(self.realizedComboBox, 1, 2, 1, 1)
        self.transAmountLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.transAmountLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.transAmountLineEdit.setObjectName(_fromUtf8("transAmountLineEdit"))
        self.gridLayout_2.addWidget(self.transAmountLineEdit, 1, 3, 1, 1)
        self.quantityLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.quantityLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.quantityLineEdit.setObjectName(_fromUtf8("quantityLineEdit"))
        self.gridLayout_2.addWidget(self.quantityLineEdit, 1, 4, 1, 1)
        self.stockIdLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.stockIdLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.stockIdLineEdit.setObjectName(_fromUtf8("stockIdLineEdit"))
        self.gridLayout_2.addWidget(self.stockIdLineEdit, 1, 5, 1, 1)
        self.priceLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.priceLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.priceLineEdit.setObjectName(_fromUtf8("priceLineEdit"))
        self.gridLayout_2.addWidget(self.priceLineEdit, 1, 6, 1, 1)
        self.commissionLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.commissionLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.commissionLineEdit.setObjectName(_fromUtf8("commissionLineEdit"))
        self.gridLayout_2.addWidget(self.commissionLineEdit, 1, 7, 1, 1)
        self.accountIdComboBox = QtGui.QComboBox(self.layoutWidget)
        self.accountIdComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.accountIdComboBox.setObjectName(_fromUtf8("accountIdComboBox"))
        self.gridLayout_2.addWidget(self.accountIdComboBox, 1, 8, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 6, 1, 1)
        self.dateEdit_expire = QtGui.QDateEdit(self.layoutWidget)
        self.dateEdit_expire.setMinimumSize(QtCore.QSize(0, 20))
        self.dateEdit_expire.setCalendarPopup(True)
        self.dateEdit_expire.setObjectName(_fromUtf8("dateEdit_expire"))
        self.gridLayout_2.addWidget(self.dateEdit_expire, 3, 0, 1, 1)
        self.atratTypeComboBox = QtGui.QComboBox(self.layoutWidget)
        self.atratTypeComboBox.setObjectName(_fromUtf8("atratTypeComboBox"))
        self.gridLayout_2.addWidget(self.atratTypeComboBox, 3, 1, 1, 1)
        self.strikePriceLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.strikePriceLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.strikePriceLineEdit.setObjectName(_fromUtf8("strikePriceLineEdit"))
        self.gridLayout_2.addWidget(self.strikePriceLineEdit, 3, 6, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 680, 401, 73))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.filterButton = QtGui.QPushButton(self.layoutWidget1)
        self.filterButton.setMinimumSize(QtCore.QSize(0, 20))
        self.filterButton.setAutoDefault(False)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.gridLayout.addWidget(self.filterButton, 1, 0, 1, 1)
        self.accountComboBox = QtGui.QComboBox(self.layoutWidget1)
        self.accountComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.accountComboBox.setObjectName(_fromUtf8("accountComboBox"))
        self.gridLayout.addWidget(self.accountComboBox, 1, 1, 1, 1)
        self.stockComboBox = QtGui.QComboBox(self.layoutWidget1)
        self.stockComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.stockComboBox.setObjectName(_fromUtf8("stockComboBox"))
        self.gridLayout.addWidget(self.stockComboBox, 1, 2, 1, 1)
        self.refreshPushButton = QtGui.QPushButton(self.layoutWidget1)
        self.refreshPushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.refreshPushButton.setAutoDefault(False)
        self.refreshPushButton.setObjectName(_fromUtf8("refreshPushButton"))
        self.gridLayout.addWidget(self.refreshPushButton, 2, 0, 1, 1)
        self.updateButton = QtGui.QPushButton(self.layoutWidget1)
        self.updateButton.setMinimumSize(QtCore.QSize(0, 20))
        self.updateButton.setAutoDefault(False)
        self.updateButton.setObjectName(_fromUtf8("updateButton"))
        self.gridLayout.addWidget(self.updateButton, 2, 1, 1, 1)
        self.cancelButton = QtGui.QPushButton(self.layoutWidget1)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 20))
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout.addWidget(self.cancelButton, 2, 2, 1, 1)
        self.deleteButton = QtGui.QPushButton(self.layoutWidget1)
        self.deleteButton.setMinimumSize(QtCore.QSize(0, 20))
        self.deleteButton.setAutoDefault(False)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.gridLayout.addWidget(self.deleteButton, 2, 3, 1, 1)
        self.closeButton = QtGui.QPushButton(self.layoutWidget1)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 20))
        self.closeButton.setAutoDefault(False)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.gridLayout.addWidget(self.closeButton, 2, 4, 1, 1)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.tableView.raise_()
        self.addButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.addButton.setText(_translate("Dialog", "Add", None))
        self.label_10.setText(_translate("Dialog", "trans_dt", None))
        self.label_2.setText(_translate("Dialog", "trans_type", None))
        self.label_9.setText(_translate("Dialog", "P/L Realized?", None))
        self.label_3.setText(_translate("Dialog", "trans_amount", None))
        self.label_4.setText(_translate("Dialog", "quantity", None))
        self.label_5.setText(_translate("Dialog", "stock_id", None))
        self.label_6.setText(_translate("Dialog", "price", None))
        self.label_7.setText(_translate("Dialog", "commission", None))
        self.label_8.setText(_translate("Dialog", "account_id", None))
        self.label_12.setText(_translate("Dialog", "expire_dt", None))
        self.label_13.setText(_translate("Dialog", "strat_type", None))
        self.label_14.setText(_translate("Dialog", "strike_price", None))
        self.label.setText(_translate("Dialog", "account_id", None))
        self.label_11.setText(_translate("Dialog", "stock_id", None))
        self.filterButton.setText(_translate("Dialog", "Filter", None))
        self.refreshPushButton.setText(_translate("Dialog", "Refresh", None))
        self.updateButton.setText(_translate("Dialog", "Update", None))
        self.cancelButton.setText(_translate("Dialog", "Cancel", None))
        self.deleteButton.setText(_translate("Dialog", "Delete", None))
        self.closeButton.setText(_translate("Dialog", "Close", None))

