# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showPortfolioRevA.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1121, 800)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(970, 710, 141, 83))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.getTransactionsButton = QtGui.QPushButton(self.layoutWidget)
        self.getTransactionsButton.setObjectName(_fromUtf8("getTransactionsButton"))
        self.verticalLayout.addWidget(self.getTransactionsButton)
        self.updatePricesButton = QtGui.QPushButton(self.layoutWidget)
        self.updatePricesButton.setObjectName(_fromUtf8("updatePricesButton"))
        self.verticalLayout.addWidget(self.updatePricesButton)
        self.genStatsButton = QtGui.QPushButton(self.layoutWidget)
        self.genStatsButton.setObjectName(_fromUtf8("genStatsButton"))
        self.verticalLayout.addWidget(self.genStatsButton)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1071, 681))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.statTab = QtGui.QWidget()
        self.statTab.setObjectName(_fromUtf8("statTab"))
        self.widget = QtGui.QWidget(self.statTab)
        self.widget.setGeometry(QtCore.QRect(40, 21, 437, 334))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.netLineEdit = QtGui.QLineEdit(self.widget)
        self.netLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.netLineEdit.setObjectName(_fromUtf8("netLineEdit"))
        self.gridLayout.addWidget(self.netLineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.depositLineEdit = QtGui.QLineEdit(self.widget)
        self.depositLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depositLineEdit.setReadOnly(True)
        self.depositLineEdit.setObjectName(_fromUtf8("depositLineEdit"))
        self.gridLayout.addWidget(self.depositLineEdit, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 1)
        self.withdrawalLineEdit = QtGui.QLineEdit(self.widget)
        self.withdrawalLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.withdrawalLineEdit.setObjectName(_fromUtf8("withdrawalLineEdit"))
        self.gridLayout.addWidget(self.withdrawalLineEdit, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.purchasesLineEdit = QtGui.QLineEdit(self.widget)
        self.purchasesLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.purchasesLineEdit.setObjectName(_fromUtf8("purchasesLineEdit"))
        self.gridLayout.addWidget(self.purchasesLineEdit, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.salesLineEdit = QtGui.QLineEdit(self.widget)
        self.salesLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.salesLineEdit.setObjectName(_fromUtf8("salesLineEdit"))
        self.gridLayout.addWidget(self.salesLineEdit, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.dividendLineEdit = QtGui.QLineEdit(self.widget)
        self.dividendLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dividendLineEdit.setObjectName(_fromUtf8("dividendLineEdit"))
        self.gridLayout.addWidget(self.dividendLineEdit, 5, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.interestLineEdit = QtGui.QLineEdit(self.widget)
        self.interestLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.interestLineEdit.setObjectName(_fromUtf8("interestLineEdit"))
        self.gridLayout.addWidget(self.interestLineEdit, 6, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.feeLineEdit = QtGui.QLineEdit(self.widget)
        self.feeLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.feeLineEdit.setObjectName(_fromUtf8("feeLineEdit"))
        self.gridLayout.addWidget(self.feeLineEdit, 7, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.cashValueLineEdit = QtGui.QLineEdit(self.widget)
        self.cashValueLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cashValueLineEdit.setReadOnly(True)
        self.cashValueLineEdit.setObjectName(_fromUtf8("cashValueLineEdit"))
        self.gridLayout.addWidget(self.cashValueLineEdit, 8, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 8, 2, 1, 1)
        self.cashPositionLineEdit = QtGui.QLineEdit(self.widget)
        self.cashPositionLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cashPositionLineEdit.setReadOnly(True)
        self.cashPositionLineEdit.setObjectName(_fromUtf8("cashPositionLineEdit"))
        self.gridLayout.addWidget(self.cashPositionLineEdit, 8, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.stockValueLineEdit = QtGui.QLineEdit(self.widget)
        self.stockValueLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stockValueLineEdit.setObjectName(_fromUtf8("stockValueLineEdit"))
        self.gridLayout.addWidget(self.stockValueLineEdit, 9, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 9, 2, 1, 1)
        self.stockPositionLineEdit = QtGui.QLineEdit(self.widget)
        self.stockPositionLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stockPositionLineEdit.setReadOnly(True)
        self.stockPositionLineEdit.setObjectName(_fromUtf8("stockPositionLineEdit"))
        self.gridLayout.addWidget(self.stockPositionLineEdit, 9, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.portValueLineEdit = QtGui.QLineEdit(self.widget)
        self.portValueLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.portValueLineEdit.setReadOnly(True)
        self.portValueLineEdit.setObjectName(_fromUtf8("portValueLineEdit"))
        self.gridLayout.addWidget(self.portValueLineEdit, 10, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 11, 0, 1, 1)
        self.absReturnLineEdit = QtGui.QLineEdit(self.widget)
        self.absReturnLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.absReturnLineEdit.setReadOnly(True)
        self.absReturnLineEdit.setObjectName(_fromUtf8("absReturnLineEdit"))
        self.gridLayout.addWidget(self.absReturnLineEdit, 11, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.widget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 12, 0, 1, 1)
        self.xirrReturnLineEdit = QtGui.QLineEdit(self.widget)
        self.xirrReturnLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xirrReturnLineEdit.setObjectName(_fromUtf8("xirrReturnLineEdit"))
        self.gridLayout.addWidget(self.xirrReturnLineEdit, 12, 1, 1, 1)
        self.tabWidget.addTab(self.statTab, _fromUtf8(""))
        self.longTab = QtGui.QWidget()
        self.longTab.setObjectName(_fromUtf8("longTab"))
        self.longView = QtGui.QTableView(self.longTab)
        self.longView.setGeometry(QtCore.QRect(0, 20, 1071, 641))
        self.longView.setAlternatingRowColors(True)
        self.longView.setObjectName(_fromUtf8("longView"))
        self.label = QtGui.QLabel(self.longTab)
        self.label.setGeometry(QtCore.QRect(10, 0, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.longTab, _fromUtf8(""))
        self.shortTab = QtGui.QWidget()
        self.shortTab.setObjectName(_fromUtf8("shortTab"))
        self.label_17 = QtGui.QLabel(self.shortTab)
        self.label_17.setGeometry(QtCore.QRect(10, 0, 81, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.shortView = QtGui.QTableView(self.shortTab)
        self.shortView.setGeometry(QtCore.QRect(-5, 21, 1071, 641))
        self.shortView.setObjectName(_fromUtf8("shortView"))
        self.tabWidget.addTab(self.shortTab, _fromUtf8(""))
        self.optionTab = QtGui.QWidget()
        self.optionTab.setObjectName(_fromUtf8("optionTab"))
        self.label_18 = QtGui.QLabel(self.optionTab)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 91, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.optionView = QtGui.QTableView(self.optionTab)
        self.optionView.setGeometry(QtCore.QRect(-5, 21, 1071, 641))
        self.optionView.setObjectName(_fromUtf8("optionView"))
        self.tabWidget.addTab(self.optionTab, _fromUtf8(""))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(40, 750, 46, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(40, 770, 46, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.accountComboBox = QtGui.QComboBox(Dialog)
        self.accountComboBox.setGeometry(QtCore.QRect(90, 770, 69, 22))
        self.accountComboBox.setObjectName(_fromUtf8("accountComboBox"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.getTransactionsButton.setText(_translate("Dialog", "Get Transactions", None))
        self.updatePricesButton.setText(_translate("Dialog", "Update Prices", None))
        self.genStatsButton.setText(_translate("Dialog", "Generate Statistics", None))
        self.label_19.setText(_translate("Dialog", "Net Deposits", None))
        self.label_2.setText(_translate("Dialog", "Total Deposits", None))
        self.label_16.setText(_translate("Dialog", "Total Withdrawals", None))
        self.label_11.setText(_translate("Dialog", "Total Purchases", None))
        self.label_12.setText(_translate("Dialog", "Total Sales", None))
        self.label_9.setText(_translate("Dialog", "Total Dividends", None))
        self.label_10.setText(_translate("Dialog", "Total Interest", None))
        self.label_15.setText(_translate("Dialog", "Total Fees", None))
        self.label_3.setText(_translate("Dialog", "Cash On Hand", None))
        self.label_7.setText(_translate("Dialog", "Cash Position", None))
        self.label_8.setText(_translate("Dialog", "Stock Value", None))
        self.label_4.setText(_translate("Dialog", "Stock Position", None))
        self.label_5.setText(_translate("Dialog", "Portfolio Value", None))
        self.label_6.setText(_translate("Dialog", "Absolute Return", None))
        self.label_20.setText(_translate("Dialog", "XIRR Return", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statTab), _translate("Dialog", "Statistics", None))
        self.label.setText(_translate("Dialog", "Long Positions:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.longTab), _translate("Dialog", "Longs", None))
        self.label_17.setText(_translate("Dialog", "Short Positions:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shortTab), _translate("Dialog", "Shorts", None))
        self.label_18.setText(_translate("Dialog", "Option Positions:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionTab), _translate("Dialog", "Options", None))
        self.label_13.setText(_translate("Dialog", "Filters:", None))
        self.label_14.setText(_translate("Dialog", "Account:", None))

